version: '2'

services:
  pw-tests:
    container_name: playwright-tests
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CI=true
      - BASE_URL=${BASE_URL}
      - API_URL=${API_URL}
      - HTTP_CREDENTIALS_USERNAME=${HTTP_CREDENTIALS_USERNAME}
      - HTTP_CREDENTIALS_PASSWORD=${HTTP_CREDENTIALS_PASSWORD}
    volumes:
      - ./playwright-report:/plawright-tests/playwright-report